name: CSDToolbox

on:
  push:
  pull_request:
    types: [ opened, ready_for_review, reopened, synchronize ]

jobs:
  MATLAB:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run CSD toolbox
        uses: matlab-actions/run-command@v2
        with:
          command: >
            addpath("CSDtoolbox/func"),
            addpath("CSDtoolbox/resource"),
            addpath("CSDtoolbox/exam"),
            ExampleCode1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ExampleCode1
          path: CSDtoolbox/exam/ExampleCode1.mat
